module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#dce9ff',
        'tertiary-fixed': '#cce5ff',
        'secondary-fixed': '#ffdbca',
        'secondary-container': '#fd761a',
        'on-secondary-fixed-variant': '#783200',
        'inverse-on-surface': '#eaf1ff',
        'primary': '#005f49',
        'surface-dim': '#cbdbf5',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'tertiary-container': '#0071ac',
        'on-primary-fixed-variant': '#00513e',
        'on-primary-fixed': '#002117',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#ffb690',
        'primary-fixed': '#98f4d3',
        'on-tertiary-container': '#e1efff',
        'surface-container-low': '#eff4ff',
        'outline-variant': '#bdc9c2',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#3e4944',
        'outline': '#6e7a74',
        'background': '#f8f9ff',
        'surface-container-highest': '#d3e4fe',
        'primary-fixed-dim': '#7cd8b8',
        'surface-container': '#e5eeff',
        'tertiary': '#005886',
        'on-tertiary-fixed-variant': '#004b73',
        'on-error-container': '#93000a',
        'primary-container': '#0d7a5f',
        'on-secondary-container': '#5c2400',
        'surface-container-lowest': '#ffffff',
        'on-background': '#0b1c30',
        'inverse-primary': '#7cd8b8',
        'surface-tint': '#006c53',
        'inverse-surface': '#213145',
        'tertiary-fixed-dim': '#93ccff',
        'on-secondary-fixed': '#341100',
        'secondary': '#9d4300',
        'surface': '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#a8ffdf',
        'on-tertiary-fixed': '#001d31',
        'on-secondary': '#ffffff',
        'surface-variant': '#d3e4fe',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      spacing: {
        'margin': '1rem',
        'space-md': '1rem',
        'gutter': '1rem',
        'space-xs': '0.25rem',
        'space-xl': '2rem',
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        'headline-xl': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
